const WORDS = [
  // ===== Приветствия и базовые фразы =====
  { hebrew: "שָׁלוֹם", russian: "привет / мир", category: "фразы" },
  { hebrew: "תּוֹדָה", russian: "спасибо", category: "фразы" },
  { hebrew: "תּוֹדָה רַבָּה", russian: "большое спасибо", category: "фразы" },
  { hebrew: "בְּבַקָּשָׁה", russian: "пожалуйста", category: "фразы" },
  { hebrew: "סְלִיחָה", russian: "извините", category: "фразы" },
  { hebrew: "בֹּקֶר טוֹב", russian: "доброе утро", category: "фразы" },
  { hebrew: "עֶרֶב טוֹב", russian: "добрый вечер", category: "фразы" },
  { hebrew: "לַיְלָה טוֹב", russian: "спокойной ночи", category: "фразы" },
  { hebrew: "לְהִתְרָאוֹת", russian: "до свидания", category: "фразы" },
  { hebrew: "בְּסֵדֶר", russian: "хорошо / ладно", category: "фразы" },
  { hebrew: "מַזָּל טוֹב", russian: "поздравляю", category: "фразы" },
  { hebrew: "בְּהַצְלָחָה", russian: "удачи", category: "фразы" },
  { hebrew: "בְּתֵאָבוֹן", russian: "приятного аппетита", category: "фразы" },
  { hebrew: "לַבְּרִיאוּת", russian: "на здоровье", category: "фразы" },
  { hebrew: "לְחַיִּים", russian: "за жизнь (тост)", category: "фразы" },
  { hebrew: "חַג שָׂמֵחַ", russian: "с праздником", category: "фразы" },
  { hebrew: "שָׁנָה טוֹבָה", russian: "хорошего года", category: "фразы" },
  { hebrew: "יוֹם הֻלֶּדֶת שָׂמֵחַ", russian: "с днём рождения", category: "фразы" },
  { hebrew: "סָבָבָה", russian: "супер / отлично (сленг)", category: "фразы" },
  { hebrew: "יַלְלָה", russian: "давай / пошли (сленг)", category: "фразы" },
  { hebrew: "בֶּאֱמֶת", russian: "правда? / действительно", category: "фразы" },
  { hebrew: "כַּמּוּבָן", russian: "конечно", category: "фразы" },
  { hebrew: "כֵּן", russian: "да", category: "фразы" },
  { hebrew: "לֹא", russian: "нет", category: "фразы" },
  { hebrew: "אוּלַי", russian: "может быть", category: "фразы" },

  // ===== Местоимения =====
  { hebrew: "אֲנִי", russian: "я", category: "местоимения" },
  { hebrew: "אַתָּה", russian: "ты (м.)", category: "местоимения" },
  { hebrew: "אַתְּ", russian: "ты (ж.)", category: "местоимения" },
  { hebrew: "הוּא", russian: "он", category: "местоимения" },
  { hebrew: "הִיא", russian: "она", category: "местоимения" },
  { hebrew: "אֲנַחְנוּ", russian: "мы", category: "местоимения" },
  { hebrew: "אַתֶּם", russian: "вы (м.)", category: "местоимения" },
  { hebrew: "אַתֶּן", russian: "вы (ж.)", category: "местоимения" },
  { hebrew: "הֵם", russian: "они (м.)", category: "местоимения" },
  { hebrew: "הֵן", russian: "они (ж.)", category: "местоимения" },
  { hebrew: "זֶה", russian: "это (м.)", category: "местоимения" },
  { hebrew: "זֹאת", russian: "это (ж.)", category: "местоимения" },
  { hebrew: "אֵלֶּה", russian: "эти", category: "местоимения" },

  // ===== Вопросительные слова =====
  { hebrew: "מִי", russian: "кто", category: "вопросы" },
  { hebrew: "מָה", russian: "что", category: "вопросы" },
  { hebrew: "אֵיפֹה", russian: "где", category: "вопросы" },
  { hebrew: "לְאָן", russian: "куда", category: "вопросы" },
  { hebrew: "מֵאַיִן", russian: "откуда", category: "вопросы" },
  { hebrew: "מָתַי", russian: "когда", category: "вопросы" },
  { hebrew: "לָמָּה", russian: "почему", category: "вопросы" },
  { hebrew: "אֵיךְ", russian: "как", category: "вопросы" },
  { hebrew: "כַּמָּה", russian: "сколько", category: "вопросы" },
  { hebrew: "אֵיזֶה", russian: "какой", category: "вопросы" },

  // ===== Числа =====
  { hebrew: "אֶחָד", russian: "один", category: "числа" },
  { hebrew: "שְׁנַיִם", russian: "два", category: "числа" },
  { hebrew: "שָׁלוֹשׁ", russian: "три", category: "числа" },
  { hebrew: "אַרְבַּע", russian: "четыре", category: "числа" },
  { hebrew: "חָמֵשׁ", russian: "пять", category: "числа" },
  { hebrew: "שֵׁשׁ", russian: "шесть", category: "числа" },
  { hebrew: "שֶׁבַע", russian: "семь", category: "числа" },
  { hebrew: "שְׁמוֹנֶה", russian: "восемь", category: "числа" },
  { hebrew: "תֵּשַׁע", russian: "девять", category: "числа" },
  { hebrew: "עֶשֶׂר", russian: "десять", category: "числа" },
  { hebrew: "אַחַת עֶשְׂרֵה", russian: "одиннадцать", category: "числа" },
  { hebrew: "שְׁתֵּים עֶשְׂרֵה", russian: "двенадцать", category: "числа" },
  { hebrew: "שְׁלוֹשׁ עֶשְׂרֵה", russian: "тринадцать", category: "числа" },
  { hebrew: "עֶשְׂרִים", russian: "двадцать", category: "числа" },
  { hebrew: "שְׁלוֹשִׁים", russian: "тридцать", category: "числа" },
  { hebrew: "אַרְבָּעִים", russian: "сорок", category: "числа" },
  { hebrew: "חֲמִשִּׁים", russian: "пятьдесят", category: "числа" },
  { hebrew: "שִׁשִּׁים", russian: "шестьдесят", category: "числа" },
  { hebrew: "שִׁבְעִים", russian: "семьдесят", category: "числа" },
  { hebrew: "שְׁמוֹנִים", russian: "восемьдесят", category: "числа" },
  { hebrew: "תִּשְׁעִים", russian: "девяносто", category: "числа" },
  { hebrew: "מֵאָה", russian: "сто", category: "числа" },
  { hebrew: "אֶלֶף", russian: "тысяча", category: "числа" },
  { hebrew: "מִילְיוֹן", russian: "миллион", category: "числа" },
  { hebrew: "רִאשׁוֹן", russian: "первый", category: "числа" },
  { hebrew: "שֵׁנִי", russian: "второй", category: "числа" },
  { hebrew: "שְׁלִישִׁי", russian: "третий", category: "числа" },

  // ===== Цвета =====
  { hebrew: "צֶבַע", russian: "цвет", category: "цвета" },
  { hebrew: "אָדֹם", russian: "красный", category: "цвета" },
  { hebrew: "כָּחֹל", russian: "синий", category: "цвета" },
  { hebrew: "יָרֹק", russian: "зелёный", category: "цвета" },
  { hebrew: "צָהֹב", russian: "жёлтый", category: "цвета" },
  { hebrew: "לָבָן", russian: "белый", category: "цвета" },
  { hebrew: "שָׁחֹר", russian: "чёрный", category: "цвета" },
  { hebrew: "כָּתֹם", russian: "оранжевый", category: "цвета" },
  { hebrew: "סָגֹל", russian: "фиолетовый", category: "цвета" },
  { hebrew: "וָרֹד", russian: "розовый", category: "цвета" },
  { hebrew: "חוּם", russian: "коричневый", category: "цвета" },
  { hebrew: "אָפֹר", russian: "серый", category: "цвета" },
  { hebrew: "זָהָב", russian: "золотой", category: "цвета" },

  // ===== Семья =====
  { hebrew: "מִשְׁפָּחָה", russian: "семья", category: "семья" },
  { hebrew: "אַבָּא", russian: "папа", category: "семья" },
  { hebrew: "אִמָּא", russian: "мама", category: "семья" },
  { hebrew: "אָב", russian: "отец", category: "семья" },
  { hebrew: "אֵם", russian: "мать", category: "семья" },
  { hebrew: "בֵּן", russian: "сын", category: "семья" },
  { hebrew: "בַּת", russian: "дочь", category: "семья" },
  { hebrew: "אָח", russian: "брат", category: "семья" },
  { hebrew: "אָחוֹת", russian: "сестра", category: "семья" },
  { hebrew: "סָבָא", russian: "дедушка", category: "семья" },
  { hebrew: "סָבְתָא", russian: "бабушка", category: "семья" },
  { hebrew: "דּוֹד", russian: "дядя", category: "семья" },
  { hebrew: "דּוֹדָה", russian: "тётя", category: "семья" },
  { hebrew: "בֶּן דּוֹד", russian: "двоюродный брат", category: "семья" },
  { hebrew: "בַּת דּוֹדָה", russian: "двоюродная сестра", category: "семья" },
  { hebrew: "נֶכֶד", russian: "внук", category: "семья" },
  { hebrew: "נֶכְדָּה", russian: "внучка", category: "семья" },
  { hebrew: "בַּעַל", russian: "муж", category: "семья" },
  { hebrew: "אִשָּׁה", russian: "жена / женщина", category: "семья" },
  { hebrew: "חָתָן", russian: "жених", category: "семья" },
  { hebrew: "כַּלָּה", russian: "невеста", category: "семья" },
  { hebrew: "תִּינוֹק", russian: "младенец", category: "семья" },
  { hebrew: "יֶלֶד", russian: "мальчик / ребёнок", category: "семья" },
  { hebrew: "יַלְדָּה", russian: "девочка", category: "семья" },
  { hebrew: "אִישׁ", russian: "мужчина / человек", category: "семья" },
  { hebrew: "חָבֵר", russian: "друг", category: "семья" },
  { hebrew: "חֲבֵרָה", russian: "подруга", category: "семья" },
  { hebrew: "שָׁכֵן", russian: "сосед", category: "семья" },

  // ===== Части тела =====
  { hebrew: "גּוּף", russian: "тело", category: "тело" },
  { hebrew: "רֹאשׁ", russian: "голова", category: "тело" },
  { hebrew: "פָּנִים", russian: "лицо", category: "тело" },
  { hebrew: "עַיִן", russian: "глаз", category: "тело" },
  { hebrew: "עֵינַיִם", russian: "глаза", category: "тело" },
  { hebrew: "אֹזֶן", russian: "ухо", category: "тело" },
  { hebrew: "אַף", russian: "нос", category: "тело" },
  { hebrew: "פֶּה", russian: "рот", category: "тело" },
  { hebrew: "שֵׁן", russian: "зуб", category: "тело" },
  { hebrew: "שִׁנַּיִם", russian: "зубы", category: "тело" },
  { hebrew: "שְׂפָתַיִם", russian: "губы", category: "тело" },
  { hebrew: "לָשׁוֹן", russian: "язык", category: "тело" },
  { hebrew: "מֵצַח", russian: "лоб", category: "тело" },
  { hebrew: "לְחִי", russian: "щека", category: "тело" },
  { hebrew: "סַנְטֵר", russian: "подбородок", category: "тело" },
  { hebrew: "צַוָּאר", russian: "шея", category: "тело" },
  { hebrew: "כָּתֵף", russian: "плечо", category: "тело" },
  { hebrew: "זְרוֹעַ", russian: "рука (от плеча)", category: "тело" },
  { hebrew: "יָד", russian: "рука (кисть)", category: "тело" },
  { hebrew: "אֶצְבַּע", russian: "палец", category: "тело" },
  { hebrew: "חָזֶה", russian: "грудь", category: "тело" },
  { hebrew: "בֶּטֶן", russian: "живот", category: "тело" },
  { hebrew: "גַּב", russian: "спина", category: "тело" },
  { hebrew: "רֶגֶל", russian: "нога", category: "тело" },
  { hebrew: "בֶּרֶךְ", russian: "колено", category: "тело" },
  { hebrew: "כַּף רֶגֶל", russian: "стопа", category: "тело" },
  { hebrew: "לֵב", russian: "сердце", category: "тело" },
  { hebrew: "דָּם", russian: "кровь", category: "тело" },
  { hebrew: "עוֹר", russian: "кожа", category: "тело" },
  { hebrew: "שֵׂעָר", russian: "волосы", category: "тело" },
  { hebrew: "עֶצֶם", russian: "кость", category: "тело" },
  { hebrew: "שְׁרִיר", russian: "мышца", category: "тело" },
  { hebrew: "מֹחַ", russian: "мозг", category: "тело" },

  // ===== Еда и напитки =====
  { hebrew: "אֹכֶל", russian: "еда", category: "еда" },
  { hebrew: "לֶחֶם", russian: "хлеб", category: "еда" },
  { hebrew: "מַיִם", russian: "вода", category: "еда" },
  { hebrew: "חָלָב", russian: "молоко", category: "еда" },
  { hebrew: "קָפֶה", russian: "кофе", category: "еда" },
  { hebrew: "תֵּה", russian: "чай", category: "еда" },
  { hebrew: "מִיץ", russian: "сок", category: "еда" },
  { hebrew: "יַיִן", russian: "вино", category: "еда" },
  { hebrew: "בִּירָה", russian: "пиво", category: "еда" },
  { hebrew: "בָּשָׂר", russian: "мясо", category: "еда" },
  { hebrew: "עוֹף", russian: "курица (мясо)", category: "еда" },
  { hebrew: "דָּג", russian: "рыба", category: "еда" },
  { hebrew: "אֹרֶז", russian: "рис", category: "еда" },
  { hebrew: "פִּיתָה", russian: "пита", category: "еда" },
  { hebrew: "סָלָט", russian: "салат", category: "еда" },
  { hebrew: "מָרָק", russian: "суп", category: "еда" },
  { hebrew: "בֵּיצָה", russian: "яйцо", category: "еда" },
  { hebrew: "גְּבִינָה", russian: "сыр", category: "еда" },
  { hebrew: "חֶמְאָה", russian: "масло (сливочное)", category: "еда" },
  { hebrew: "שֶׁמֶן", russian: "масло (растительное)", category: "еда" },
  { hebrew: "מֶלַח", russian: "соль", category: "еда" },
  { hebrew: "פִּלְפֵּל", russian: "перец", category: "еда" },
  { hebrew: "סֻכָּר", russian: "сахар", category: "еда" },
  { hebrew: "תַּפּוּחַ", russian: "яблоко", category: "еда" },
  { hebrew: "בָּנָנָה", russian: "банан", category: "еда" },
  { hebrew: "תַּפּוּז", russian: "апельсин", category: "еда" },
  { hebrew: "עֲנָבִים", russian: "виноград", category: "еда" },
  { hebrew: "אֲבַטִּיחַ", russian: "арбуз", category: "еда" },
  { hebrew: "לִימוֹן", russian: "лимон", category: "еда" },
  { hebrew: "תּוּת", russian: "клубника", category: "еда" },
  { hebrew: "אֲגָס", russian: "груша", category: "еда" },
  { hebrew: "אֲפַרְסֵק", russian: "персик", category: "еда" },
  { hebrew: "מָנְגּוֹ", russian: "манго", category: "еда" },
  { hebrew: "עֲגָבָנִיָּה", russian: "помидор", category: "еда" },
  { hebrew: "מְלָפְפוֹן", russian: "огурец", category: "еда" },
  { hebrew: "בָּצָל", russian: "лук", category: "еда" },
  { hebrew: "שׁוּם", russian: "чеснок", category: "еда" },
  { hebrew: "גֶּזֶר", russian: "морковь", category: "еда" },
  { hebrew: "תַּפּוּחַ אֲדָמָה", russian: "картофель", category: "еда" },
  { hebrew: "פִּטְרִיָּה", russian: "гриб", category: "еда" },
  { hebrew: "חָסָה", russian: "салат (латук)", category: "еда" },
  { hebrew: "עוּגָה", russian: "торт / пирог", category: "еда" },
  { hebrew: "עוּגִיָּה", russian: "печенье", category: "еда" },
  { hebrew: "שׁוֹקוֹלָד", russian: "шоколад", category: "еда" },
  { hebrew: "גְּלִידָה", russian: "мороженое", category: "еда" },
  { hebrew: "דְּבַשׁ", russian: "мёд", category: "еда" },
  { hebrew: "רִיבָה", russian: "варенье", category: "еда" },
  { hebrew: "אֱגוֹז", russian: "орех", category: "еда" },
  { hebrew: "פִּיצָה", russian: "пицца", category: "еда" },
  { hebrew: "הַמְבּוּרְגֶּר", russian: "гамбургер", category: "еда" },
  { hebrew: "חוּמוּס", russian: "хумус", category: "еда" },
  { hebrew: "פָלָאפֶל", russian: "фалафель", category: "еда" },
  { hebrew: "שַׁוְוַרְמָה", russian: "шаварма", category: "еда" },
  { hebrew: "טְחִינָה", russian: "тхина", category: "еда" },
  { hebrew: "אֲרוּחָה", russian: "приём пищи", category: "еда" },
  { hebrew: "אֲרוּחַת בֹּקֶר", russian: "завтрак", category: "еда" },
  { hebrew: "אֲרוּחַת צָהֳרַיִם", russian: "обед", category: "еда" },
  { hebrew: "אֲרוּחַת עֶרֶב", russian: "ужин", category: "еда" },

  // ===== Животные =====
  { hebrew: "חַיָּה", russian: "животное", category: "животные" },
  { hebrew: "חָתוּל", russian: "кот / кошка", category: "животные" },
  { hebrew: "כֶּלֶב", russian: "собака", category: "животные" },
  { hebrew: "צִפּוֹר", russian: "птица", category: "животные" },
  { hebrew: "סוּס", russian: "лошадь", category: "животные" },
  { hebrew: "פָּרָה", russian: "корова", category: "животные" },
  { hebrew: "כֶּבֶשׂ", russian: "овца", category: "животные" },
  { hebrew: "עֵז", russian: "коза", category: "животные" },
  { hebrew: "חֲזִיר", russian: "свинья", category: "животные" },
  { hebrew: "תַּרְנְגוֹל", russian: "петух", category: "животные" },
  { hebrew: "תַּרְנְגוֹלֶת", russian: "курица", category: "животные" },
  { hebrew: "בַּרְוָז", russian: "утка", category: "животные" },
  { hebrew: "אַרְנֶבֶת", russian: "кролик", category: "животные" },
  { hebrew: "נָחָשׁ", russian: "змея", category: "животные" },
  { hebrew: "דֻּב", russian: "медведь", category: "животные" },
  { hebrew: "אַרְיֵה", russian: "лев", category: "животные" },
  { hebrew: "פִּיל", russian: "слон", category: "животные" },
  { hebrew: "קוֹף", russian: "обезьяна", category: "животные" },
  { hebrew: "זְאֵב", russian: "волк", category: "животные" },
  { hebrew: "שׁוּעָל", russian: "лиса", category: "животные" },
  { hebrew: "צָב", russian: "черепаха", category: "животные" },
  { hebrew: "דְּבוֹרָה", russian: "пчела", category: "животные" },
  { hebrew: "פַּרְפַּר", russian: "бабочка", category: "животные" },
  { hebrew: "נְמָלָה", russian: "муравей", category: "животные" },
  { hebrew: "עַכָּבִישׁ", russian: "паук", category: "животные" },
  { hebrew: "יוֹנָה", russian: "голубь", category: "животные" },
  { hebrew: "נֶשֶׁר", russian: "орёл", category: "животные" },
  { hebrew: "גָּמָל", russian: "верблюд", category: "животные" },

  // ===== Природа и погода =====
  { hebrew: "שֶׁמֶשׁ", russian: "солнце", category: "природа" },
  { hebrew: "יָרֵחַ", russian: "луна", category: "природа" },
  { hebrew: "כּוֹכָב", russian: "звезда", category: "природа" },
  { hebrew: "שָׁמַיִם", russian: "небо", category: "природа" },
  { hebrew: "אֶרֶץ", russian: "земля / страна", category: "природа" },
  { hebrew: "עֵץ", russian: "дерево", category: "природа" },
  { hebrew: "פֶּרַח", russian: "цветок", category: "природа" },
  { hebrew: "דֶּשֶׁא", russian: "трава", category: "природа" },
  { hebrew: "יַעַר", russian: "лес", category: "природа" },
  { hebrew: "הַר", russian: "гора", category: "природа" },
  { hebrew: "גִּבְעָה", russian: "холм", category: "природа" },
  { hebrew: "נָהָר", russian: "река", category: "природа" },
  { hebrew: "יָם", russian: "море", category: "природа" },
  { hebrew: "אֲגַם", russian: "озеро", category: "природа" },
  { hebrew: "מִדְבָּר", russian: "пустыня", category: "природа" },
  { hebrew: "אִי", russian: "остров", category: "природа" },
  { hebrew: "חוֹל", russian: "песок", category: "природа" },
  { hebrew: "אֶבֶן", russian: "камень", category: "природа" },
  { hebrew: "סֶלַע", russian: "скала", category: "природа" },
  { hebrew: "גֶּשֶׁם", russian: "дождь", category: "природа" },
  { hebrew: "שֶׁלֶג", russian: "снег", category: "природа" },
  { hebrew: "רוּחַ", russian: "ветер / дух", category: "природа" },
  { hebrew: "סְעָרָה", russian: "буря", category: "природа" },
  { hebrew: "עָנָן", russian: "облако", category: "природа" },
  { hebrew: "בָּרָק", russian: "молния", category: "природа" },
  { hebrew: "רַעַם", russian: "гром", category: "природа" },
  { hebrew: "אֵשׁ", russian: "огонь", category: "природа" },
  { hebrew: "אוֹר", russian: "свет", category: "природа" },
  { hebrew: "צֵל", russian: "тень", category: "природа" },
  { hebrew: "קֶשֶׁת", russian: "радуга", category: "природа" },
  { hebrew: "אֲוִיר", russian: "воздух", category: "природа" },

  // ===== Дом и мебель =====
  { hebrew: "בַּיִת", russian: "дом", category: "дом" },
  { hebrew: "דִּירָה", russian: "квартира", category: "дом" },
  { hebrew: "חֶדֶר", russian: "комната", category: "дом" },
  { hebrew: "מִטְבָּח", russian: "кухня", category: "дом" },
  { hebrew: "סָלוֹן", russian: "гостиная", category: "дом" },
  { hebrew: "חֲדַר שֵׁנָה", russian: "спальня", category: "дом" },
  { hebrew: "חֲדַר אַמְבַּטְיָה", russian: "ванная", category: "дом" },
  { hebrew: "שֵׁירוּתִים", russian: "туалет", category: "дом" },
  { hebrew: "מִרְפֶּסֶת", russian: "балкон", category: "дом" },
  { hebrew: "גַּג", russian: "крыша", category: "дом" },
  { hebrew: "גָּדֵר", russian: "забор", category: "дом" },
  { hebrew: "גִּנָּה", russian: "сад", category: "дом" },
  { hebrew: "שֻׁלְחָן", russian: "стол", category: "дом" },
  { hebrew: "כִּסֵּא", russian: "стул", category: "дом" },
  { hebrew: "כּוֹרְסָה", russian: "кресло", category: "дом" },
  { hebrew: "סַפָּה", russian: "диван", category: "дом" },
  { hebrew: "מִטָּה", russian: "кровать", category: "дом" },
  { hebrew: "אָרוֹן", russian: "шкаф", category: "дом" },
  { hebrew: "מַדָּף", russian: "полка", category: "дом" },
  { hebrew: "מְקָרֵר", russian: "холодильник", category: "дом" },
  { hebrew: "תַּנּוּר", russian: "духовка", category: "дом" },
  { hebrew: "כִּיּוֹר", russian: "раковина", category: "дом" },
  { hebrew: "מְכוֹנַת כְּבִיסָה", russian: "стиральная машина", category: "дом" },
  { hebrew: "מַזְגָּן", russian: "кондиционер", category: "дом" },
  { hebrew: "מַפְתֵּחַ", russian: "ключ", category: "дом" },
  { hebrew: "חַלּוֹן", russian: "окно", category: "дом" },
  { hebrew: "דֶּלֶת", russian: "дверь", category: "дом" },
  { hebrew: "קִיר", russian: "стена", category: "дом" },
  { hebrew: "רִצְפָּה", russian: "пол", category: "дом" },
  { hebrew: "תִּקְרָה", russian: "потолок", category: "дом" },
  { hebrew: "מַדְרֵגוֹת", russian: "лестница", category: "дом" },
  { hebrew: "מַעֲלִית", russian: "лифт", category: "дом" },
  { hebrew: "מַקְלַחַת", russian: "душ", category: "дом" },
  { hebrew: "מַגֶּבֶת", russian: "полотенце", category: "дом" },
  { hebrew: "כָּרִית", russian: "подушка", category: "дом" },
  { hebrew: "שְׂמִיכָה", russian: "одеяло", category: "дом" },
  { hebrew: "מִרְאָה", russian: "зеркало", category: "дом" },
  { hebrew: "מַנּוֹרָה", russian: "лампа / светильник", category: "дом" },

  // ===== Одежда =====
  { hebrew: "בֶּגֶד", russian: "одежда", category: "одежда" },
  { hebrew: "חֻלְצָה", russian: "рубашка", category: "одежда" },
  { hebrew: "מִכְנָסַיִם", russian: "брюки", category: "одежда" },
  { hebrew: "חֲצָאִית", russian: "юбка", category: "одежда" },
  { hebrew: "שִׂמְלָה", russian: "платье", category: "одежда" },
  { hebrew: "מְעִיל", russian: "пальто / куртка", category: "одежда" },
  { hebrew: "סְוֶדֶר", russian: "свитер", category: "одежда" },
  { hebrew: "חוֹלְצַת טִי", russian: "футболка", category: "одежда" },
  { hebrew: "מִכְנָסַיִם קְצָרִים", russian: "шорты", category: "одежда" },
  { hebrew: "גַּרְבַּיִם", russian: "носки", category: "одежда" },
  { hebrew: "נַעֲלַיִם", russian: "обувь / туфли", category: "одежда" },
  { hebrew: "סַנְדָּלִים", russian: "сандалии", category: "одежда" },
  { hebrew: "מַגָּפַיִם", russian: "сапоги", category: "одежда" },
  { hebrew: "כּוֹבַע", russian: "шляпа / кепка", category: "одежда" },
  { hebrew: "צָעִיף", russian: "шарф", category: "одежда" },
  { hebrew: "כְּפָפוֹת", russian: "перчатки", category: "одежда" },
  { hebrew: "חֲגוֹרָה", russian: "ремень", category: "одежда" },
  { hebrew: "מִשְׁקָפַיִם", russian: "очки", category: "одежда" },
  { hebrew: "שָׁעוֹן", russian: "часы (наручные)", category: "одежда" },
  { hebrew: "טַבַּעַת", russian: "кольцо", category: "одежда" },
  { hebrew: "שַׁרְשֶׁרֶת", russian: "цепочка / ожерелье", category: "одежда" },
  { hebrew: "תִּיק", russian: "сумка", category: "одежда" },

  // ===== Транспорт =====
  { hebrew: "מְכוֹנִית", russian: "автомобиль", category: "транспорт" },
  { hebrew: "אוֹטוֹבּוּס", russian: "автобус", category: "транспорт" },
  { hebrew: "רַכֶּבֶת", russian: "поезд", category: "транспорт" },
  { hebrew: "מוֹנִית", russian: "такси", category: "транспорт" },
  { hebrew: "אוֹפַנַּיִם", russian: "велосипед", category: "транспорт" },
  { hebrew: "אוֹפָנוֹעַ", russian: "мотоцикл", category: "транспорт" },
  { hebrew: "מָטוֹס", russian: "самолёт", category: "транспорт" },
  { hebrew: "אֳנִיָּה", russian: "корабль", category: "транспорт" },
  { hebrew: "סִירָה", russian: "лодка", category: "транспорт" },
  { hebrew: "רַמְזוֹר", russian: "светофор", category: "транспорт" },
  { hebrew: "כְּבִישׁ", russian: "шоссе / дорога", category: "транспорт" },
  { hebrew: "מִדְרָכָה", russian: "тротуар", category: "транспорт" },
  { hebrew: "תַּחֲנָה", russian: "станция / остановка", category: "транспорт" },
  { hebrew: "נְמַל תְּעוּפָה", russian: "аэропорт", category: "транспорт" },
  { hebrew: "חֲנָיָה", russian: "парковка", category: "транспорт" },
  { hebrew: "דֶּלֶק", russian: "топливо / бензин", category: "транспорт" },
  { hebrew: "נֶהָג", russian: "водитель", category: "транспорт" },
  { hebrew: "נוֹסֵעַ", russian: "пассажир", category: "транспорт" },
  { hebrew: "כַּרְטִיס", russian: "билет", category: "транспорт" },

  // ===== Город и места =====
  { hebrew: "עִיר", russian: "город", category: "город" },
  { hebrew: "כְּפָר", russian: "деревня", category: "город" },
  { hebrew: "רְחוֹב", russian: "улица", category: "город" },
  { hebrew: "כִּכָּר", russian: "площадь", category: "город" },
  { hebrew: "גֶּשֶׁר", russian: "мост", category: "город" },
  { hebrew: "דֶּרֶךְ", russian: "дорога / путь", category: "город" },
  { hebrew: "מְדִינָה", russian: "государство", category: "город" },
  { hebrew: "בִּנְיָן", russian: "здание", category: "город" },
  { hebrew: "בֵּית סֵפֶר", russian: "школа", category: "город" },
  { hebrew: "אוּנִיבֶרְסִיטָה", russian: "университет", category: "город" },
  { hebrew: "בֵּית חוֹלִים", russian: "больница", category: "город" },
  { hebrew: "מִרְפָּאָה", russian: "поликлиника", category: "город" },
  { hebrew: "בֵּית מָלוֹן", russian: "гостиница", category: "город" },
  { hebrew: "מִסְעָדָה", russian: "ресторан", category: "город" },
  { hebrew: "בֵּית קָפֶה", russian: "кафе", category: "город" },
  { hebrew: "חֲנוּת", russian: "магазин", category: "город" },
  { hebrew: "סוּפֶּרְמָרְקֶט", russian: "супермаркет", category: "город" },
  { hebrew: "שׁוּק", russian: "рынок", category: "город" },
  { hebrew: "בַּנְק", russian: "банк", category: "город" },
  { hebrew: "דֹּאַר", russian: "почта", category: "город" },
  { hebrew: "מִשְׂרָד", russian: "офис", category: "город" },
  { hebrew: "מוּזֵאוֹן", russian: "музей", category: "город" },
  { hebrew: "סִפְרִיָּה", russian: "библиотека", category: "город" },
  { hebrew: "בֵּית כְּנֶסֶת", russian: "синагога", category: "город" },
  { hebrew: "קוֹלְנוֹעַ", russian: "кинотеатр", category: "город" },
  { hebrew: "תֵּיאַטְרוֹן", russian: "театр", category: "город" },
  { hebrew: "פַּארְק", russian: "парк", category: "город" },
  { hebrew: "חוֹף", russian: "пляж / берег", category: "город" },
  { hebrew: "בְּרֵכָה", russian: "бассейн", category: "город" },
  { hebrew: "מִגְרָשׁ", russian: "площадка / поле", category: "город" },

  // ===== Время и календарь =====
  { hebrew: "זְמַן", russian: "время", category: "время" },
  { hebrew: "שָׁעָה", russian: "час", category: "время" },
  { hebrew: "דַּקָּה", russian: "минута", category: "время" },
  { hebrew: "שְׁנִיָּה", russian: "секунда", category: "время" },
  { hebrew: "יוֹם", russian: "день", category: "время" },
  { hebrew: "שָׁבוּעַ", russian: "неделя", category: "время" },
  { hebrew: "חֹדֶשׁ", russian: "месяц", category: "время" },
  { hebrew: "שָׁנָה", russian: "год", category: "время" },
  { hebrew: "בֹּקֶר", russian: "утро", category: "время" },
  { hebrew: "צָהֳרַיִם", russian: "полдень", category: "время" },
  { hebrew: "אַחַר הַצָּהֳרַיִם", russian: "после обеда", category: "время" },
  { hebrew: "עֶרֶב", russian: "вечер", category: "время" },
  { hebrew: "לַיְלָה", russian: "ночь", category: "время" },
  { hebrew: "הַיּוֹם", russian: "сегодня", category: "время" },
  { hebrew: "אֶתְמוֹל", russian: "вчера", category: "время" },
  { hebrew: "מָחָר", russian: "завтра", category: "время" },
  { hebrew: "עַכְשָׁיו", russian: "сейчас", category: "время" },
  { hebrew: "תָּמִיד", russian: "всегда", category: "время" },
  { hebrew: "לִפְעָמִים", russian: "иногда", category: "время" },
  { hebrew: "אַף פַּעַם", russian: "никогда", category: "время" },
  { hebrew: "מֻקְדָּם", russian: "рано", category: "время" },
  { hebrew: "מְאֻחָר", russian: "поздно", category: "время" },
  { hebrew: "יוֹם רִאשׁוֹן", russian: "воскресенье", category: "время" },
  { hebrew: "יוֹם שֵׁנִי", russian: "понедельник", category: "время" },
  { hebrew: "יוֹם שְׁלִישִׁי", russian: "вторник", category: "время" },
  { hebrew: "יוֹם רְבִיעִי", russian: "среда", category: "время" },
  { hebrew: "יוֹם חֲמִישִׁי", russian: "четверг", category: "время" },
  { hebrew: "יוֹם שִׁשִּׁי", russian: "пятница", category: "время" },
  { hebrew: "שַׁבָּת", russian: "суббота", category: "время" },

  // ===== Профессии =====
  { hebrew: "מוֹרֶה", russian: "учитель", category: "профессии" },
  { hebrew: "תַּלְמִיד", russian: "ученик", category: "профессии" },
  { hebrew: "רוֹפֵא", russian: "врач", category: "профессии" },
  { hebrew: "אָחוֹת רְפוּאִית", russian: "медсестра", category: "профессии" },
  { hebrew: "מְהַנְדֵּס", russian: "инженер", category: "профессии" },
  { hebrew: "עוֹרֵךְ דִּין", russian: "адвокат", category: "профессии" },
  { hebrew: "שׁוֹפֵט", russian: "судья", category: "профессии" },
  { hebrew: "שׁוֹטֵר", russian: "полицейский", category: "профессии" },
  { hebrew: "חַיָּל", russian: "солдат", category: "профессии" },
  { hebrew: "כַּבַּאי", russian: "пожарный", category: "профессии" },
  { hebrew: "טַבָּח", russian: "повар", category: "профессии" },
  { hebrew: "עִתּוֹנַאי", russian: "журналист", category: "профессии" },
  { hebrew: "צַלָּם", russian: "фотограф", category: "профессии" },
  { hebrew: "זַמָּר", russian: "певец", category: "профессии" },
  { hebrew: "שַׂחְקָן", russian: "актёр", category: "профессии" },
  { hebrew: "צַיָּר", russian: "художник", category: "профессии" },
  { hebrew: "סוֹפֵר", russian: "писатель", category: "профессии" },
  { hebrew: "מְדַעָן", russian: "учёный", category: "профессии" },
  { hebrew: "חַקְלַאי", russian: "фермер", category: "профессии" },
  { hebrew: "בַּנַּאי", russian: "строитель", category: "профессии" },
  { hebrew: "חַשְׁמַלַּאי", russian: "электрик", category: "профессии" },
  { hebrew: "אִינְסְטָלָטוֹר", russian: "сантехник", category: "профессии" },
  { hebrew: "תַּיָּר", russian: "турист", category: "профессии" },
  { hebrew: "מְתַכְנֵת", russian: "программист", category: "профессии" },
  { hebrew: "רוֹאֵה חֶשְׁבּוֹן", russian: "бухгалтер", category: "профессии" },

  // ===== Эмоции и чувства =====
  { hebrew: "שָׂמֵחַ", russian: "весёлый / рад", category: "эмоции" },
  { hebrew: "עָצוּב", russian: "грустный", category: "эмоции" },
  { hebrew: "כָּעוּס", russian: "злой", category: "эмоции" },
  { hebrew: "מְפֻחָד", russian: "испуганный", category: "эмоции" },
  { hebrew: "עָיֵף", russian: "усталый", category: "эмоции" },
  { hebrew: "רָעֵב", russian: "голодный", category: "эмоции" },
  { hebrew: "צָמֵא", russian: "жаждущий", category: "эмоции" },
  { hebrew: "חוֹלֶה", russian: "больной", category: "эмоции" },
  { hebrew: "בָּרִיא", russian: "здоровый", category: "эмоции" },
  { hebrew: "מְאֻשָּׁר", russian: "счастливый", category: "эмоции" },
  { hebrew: "גֵּאֶה", russian: "гордый", category: "эмоции" },
  { hebrew: "מֻפְתָּע", russian: "удивлённый", category: "эмоции" },
  { hebrew: "מְבוּלְבָּל", russian: "растерянный", category: "эмоции" },
  { hebrew: "מְעוּנְיָן", russian: "заинтересованный", category: "эмоции" },
  { hebrew: "מְשׁוּעֲמָם", russian: "скучающий", category: "эмоции" },
  { hebrew: "נֶחְמָד", russian: "милый / приятный", category: "эмоции" },
  { hebrew: "אַהֲבָה", russian: "любовь", category: "эмоции" },
  { hebrew: "שִׂנְאָה", russian: "ненависть", category: "эмоции" },
  { hebrew: "שִׂמְחָה", russian: "радость", category: "эмоции" },
  { hebrew: "עֶצֶב", russian: "грусть / печаль", category: "эмоции" },
  { hebrew: "כַּעַס", russian: "гнев", category: "эмоции" },
  { hebrew: "פַּחַד", russian: "страх", category: "эмоции" },
  { hebrew: "תִּקְוָה", russian: "надежда", category: "эмоции" },
  { hebrew: "בִּטָּחוֹן", russian: "уверенность", category: "эмоции" },
  { hebrew: "קִנְאָה", russian: "ревность / зависть", category: "эмоции" },

  // ===== Глаголы =====
  { hebrew: "לֶאֱכֹל", russian: "есть (кушать)", category: "глаголы" },
  { hebrew: "לִשְׁתּוֹת", russian: "пить", category: "глаголы" },
  { hebrew: "לִישֹׁן", russian: "спать", category: "глаголы" },
  { hebrew: "לָקוּם", russian: "вставать", category: "глаголы" },
  { hebrew: "לָלֶכֶת", russian: "идти", category: "глаголы" },
  { hebrew: "לָרוּץ", russian: "бежать", category: "глаголы" },
  { hebrew: "לָבוֹא", russian: "приходить", category: "глаголы" },
  { hebrew: "לָשֶׁבֶת", russian: "сидеть", category: "глаголы" },
  { hebrew: "לַעֲמֹד", russian: "стоять", category: "глаголы" },
  { hebrew: "לְדַבֵּר", russian: "говорить", category: "глаголы" },
  { hebrew: "לֹאמַר", russian: "сказать", category: "глаголы" },
  { hebrew: "לִשְׁמֹעַ", russian: "слышать", category: "глаголы" },
  { hebrew: "לִרְאוֹת", russian: "видеть", category: "глаголы" },
  { hebrew: "לִקְרֹא", russian: "читать / звать", category: "глаголы" },
  { hebrew: "לִכְתֹּב", russian: "писать", category: "глаголы" },
  { hebrew: "לִלְמֹד", russian: "учиться", category: "глаголы" },
  { hebrew: "לְלַמֵּד", russian: "учить (кого-то)", category: "глаголы" },
  { hebrew: "לַעֲבֹד", russian: "работать", category: "глаголы" },
  { hebrew: "לְשַׂחֵק", russian: "играть", category: "глаголы" },
  { hebrew: "לָשִׁיר", russian: "петь", category: "глаголы" },
  { hebrew: "לִרְקוֹד", russian: "танцевать", category: "глаголы" },
  { hebrew: "לְבַשֵּׁל", russian: "готовить (еду)", category: "глаголы" },
  { hebrew: "לִנְסוֹעַ", russian: "ехать", category: "глаголы" },
  { hebrew: "לָטוּס", russian: "лететь", category: "глаголы" },
  { hebrew: "לִפְתֹּחַ", russian: "открывать", category: "глаголы" },
  { hebrew: "לִסְגֹּר", russian: "закрывать", category: "глаголы" },
  { hebrew: "לָתֵת", russian: "давать", category: "глаголы" },
  { hebrew: "לָקַחַת", russian: "брать", category: "глаголы" },
  { hebrew: "לִקְנוֹת", russian: "покупать", category: "глаголы" },
  { hebrew: "לִמְכֹּר", russian: "продавать", category: "глаголы" },
  { hebrew: "לְשַׁלֵּם", russian: "платить", category: "глаголы" },
  { hebrew: "לַחְשֹׁב", russian: "думать", category: "глаголы" },
  { hebrew: "לָדַעַת", russian: "знать", category: "глаголы" },
  { hebrew: "לְהָבִין", russian: "понимать", category: "глаголы" },
  { hebrew: "לִזְכֹּר", russian: "помнить", category: "глаголы" },
  { hebrew: "לִשְׁכֹּחַ", russian: "забывать", category: "глаголы" },
  { hebrew: "לְחַפֵּשׂ", russian: "искать", category: "глаголы" },
  { hebrew: "לִמְצֹא", russian: "находить", category: "глаголы" },
  { hebrew: "לַעֲזֹר", russian: "помогать", category: "глаголы" },
  { hebrew: "לְהַזְמִין", russian: "заказывать / приглашать", category: "глаголы" },
  { hebrew: "לְהַמְתִּין", russian: "ждать", category: "глаголы" },
  { hebrew: "לְהַתְחִיל", russian: "начинать", category: "глаголы" },
  { hebrew: "לִגְמֹר", russian: "заканчивать", category: "глаголы" },
  { hebrew: "לַחְזֹר", russian: "возвращаться", category: "глаголы" },
  { hebrew: "לְהַגִּיעַ", russian: "прибывать", category: "глаголы" },
  { hebrew: "לָצֵאת", russian: "выходить", category: "глаголы" },
  { hebrew: "לְהִכָּנֵס", russian: "входить", category: "глаголы" },
  { hebrew: "לָשִׂים", russian: "класть / ставить", category: "глаголы" },
  { hebrew: "לִשְׁאוֹל", russian: "спрашивать", category: "глаголы" },
  { hebrew: "לַעֲנוֹת", russian: "отвечать", category: "глаголы" },
  { hebrew: "לְהַסְבִּיר", russian: "объяснять", category: "глаголы" },
  { hebrew: "לִבְחוֹר", russian: "выбирать", category: "глаголы" },
  { hebrew: "לְהַחְלִיט", russian: "решать", category: "глаголы" },
  { hebrew: "לְנַסּוֹת", russian: "пробовать / пытаться", category: "глаголы" },
  { hebrew: "לְהִשְׁתַּמֵּשׁ", russian: "использовать", category: "глаголы" },
  { hebrew: "לְהַפְסִיק", russian: "прекращать", category: "глаголы" },
  { hebrew: "לְהַמְשִׁיךְ", russian: "продолжать", category: "глаголы" },
  { hebrew: "לְקַבֵּל", russian: "получать", category: "глаголы" },
  { hebrew: "לִשְׁלֹחַ", russian: "отправлять", category: "глаголы" },
  { hebrew: "לְהַרְגִּישׁ", russian: "чувствовать", category: "глаголы" },
  { hebrew: "לֶאֱהֹב", russian: "любить", category: "глаголы" },
  { hebrew: "לִשְׂנֹא", russian: "ненавидеть", category: "глаголы" },
  { hebrew: "לְהִתְחַתֵּן", russian: "жениться / выходить замуж", category: "глаголы" },
  { hebrew: "לָגוּר", russian: "жить (проживать)", category: "глаголы" },
  { hebrew: "לִחְיוֹת", russian: "жить (быть живым)", category: "глаголы" },
  { hebrew: "לָמוּת", russian: "умирать", category: "глаголы" },
  { hebrew: "לִגְדֹּל", russian: "расти", category: "глаголы" },
  { hebrew: "לִבְנוֹת", russian: "строить", category: "глаголы" },
  { hebrew: "לִשְׁבֹּר", russian: "ломать", category: "глаголы" },
  { hebrew: "לְתַקֵּן", russian: "чинить", category: "глаголы" },
  { hebrew: "לִפְגֹּשׁ", russian: "встречать", category: "глаголы" },
  { hebrew: "לְהִפָּרֵד", russian: "прощаться", category: "глаголы" },
  { hebrew: "לְצַלְצֵל", russian: "звонить", category: "глаголы" },
  { hebrew: "לְהִתְלַבֵּשׁ", russian: "одеваться", category: "глаголы" },
  { hebrew: "לְהִתְרַחֵץ", russian: "мыться", category: "глаголы" },
  { hebrew: "לִצְחוֹק", russian: "смеяться", category: "глаголы" },
  { hebrew: "לִבְכּוֹת", russian: "плакать", category: "глаголы" },
  { hebrew: "לְהַאֲמִין", russian: "верить", category: "глаголы" },
  { hebrew: "לְקַוּוֹת", russian: "надеяться", category: "глаголы" },
  { hebrew: "לְסַפֵּר", russian: "рассказывать", category: "глаголы" },
  { hebrew: "לִטְעֹם", russian: "пробовать (на вкус)", category: "глаголы" },
  { hebrew: "לָגַעַת", russian: "трогать", category: "глаголы" },
  { hebrew: "לְהָרִיחַ", russian: "нюхать / пахнуть", category: "глаголы" },
  { hebrew: "לִזְרוֹק", russian: "бросать", category: "глаголы" },
  { hebrew: "לִתְפֹּס", russian: "ловить / хватать", category: "глаголы" },
  { hebrew: "לִדְחוֹף", russian: "толкать", category: "глаголы" },
  { hebrew: "לִמְשׁוֹךְ", russian: "тянуть", category: "глаголы" },
  { hebrew: "לָשֵׂאת", russian: "нести", category: "глаголы" },
  { hebrew: "לִנְהוֹג", russian: "водить (машину)", category: "глаголы" },
  { hebrew: "לְהַדְלִיק", russian: "зажигать / включать", category: "глаголы" },
  { hebrew: "לְכַבּוֹת", russian: "тушить / выключать", category: "глаголы" },
  { hebrew: "לְנַקּוֹת", russian: "чистить / убирать", category: "глаголы" },
  { hebrew: "לְהִתְפַּלֵּל", russian: "молиться", category: "глаголы" },
  { hebrew: "לָצוּם", russian: "поститься", category: "глаголы" },
  { hebrew: "לַחְלוֹם", russian: "мечтать / видеть сон", category: "глаголы" },
  { hebrew: "לְטַיֵּל", russian: "гулять / путешествовать", category: "глаголы" },

  // ===== Прилагательные =====
  { hebrew: "גָּדוֹל", russian: "большой", category: "прилагательные" },
  { hebrew: "קָטָן", russian: "маленький", category: "прилагательные" },
  { hebrew: "טוֹב", russian: "хороший", category: "прилагательные" },
  { hebrew: "רַע", russian: "плохой", category: "прилагательные" },
  { hebrew: "יָפֶה", russian: "красивый", category: "прилагательные" },
  { hebrew: "מְכוֹעָר", russian: "некрасивый", category: "прилагательные" },
  { hebrew: "חָדָשׁ", russian: "новый", category: "прилагательные" },
  { hebrew: "יָשָׁן", russian: "старый (о вещи)", category: "прилагательные" },
  { hebrew: "צָעִיר", russian: "молодой", category: "прилагательные" },
  { hebrew: "זָקֵן", russian: "старый (о человеке)", category: "прилагательные" },
  { hebrew: "חַם", russian: "горячий / жаркий", category: "прилагательные" },
  { hebrew: "קַר", russian: "холодный", category: "прилагательные" },
  { hebrew: "גָּבוֹהַּ", russian: "высокий", category: "прилагательные" },
  { hebrew: "נָמוּךְ", russian: "низкий", category: "прилагательные" },
  { hebrew: "אָרֹךְ", russian: "длинный", category: "прилагательные" },
  { hebrew: "קָצָר", russian: "короткий", category: "прилагательные" },
  { hebrew: "רָחָב", russian: "широкий", category: "прилагательные" },
  { hebrew: "צַר", russian: "узкий", category: "прилагательные" },
  { hebrew: "כָּבֵד", russian: "тяжёлый", category: "прилагательные" },
  { hebrew: "קַל", russian: "лёгкий", category: "прилагательные" },
  { hebrew: "מָהִיר", russian: "быстрый", category: "прилагательные" },
  { hebrew: "אִטִּי", russian: "медленный", category: "прилагательные" },
  { hebrew: "חָזָק", russian: "сильный", category: "прилагательные" },
  { hebrew: "חָלָשׁ", russian: "слабый", category: "прилагательные" },
  { hebrew: "קָשֶׁה", russian: "трудный / твёрдый", category: "прилагательные" },
  { hebrew: "רַךְ", russian: "мягкий", category: "прилагательные" },
  { hebrew: "חָשׁוּב", russian: "важный", category: "прилагательные" },
  { hebrew: "מְיֻחָד", russian: "особенный", category: "прилагательные" },
  { hebrew: "רָגִיל", russian: "обычный", category: "прилагательные" },
  { hebrew: "נָכוֹן", russian: "правильный", category: "прилагательные" },
  { hebrew: "פָּשׁוּט", russian: "простой", category: "прилагательные" },
  { hebrew: "מְסֻבָּךְ", russian: "сложный", category: "прилагательные" },
  { hebrew: "מְעַנְיֵן", russian: "интересный", category: "прилагательные" },
  { hebrew: "מְשַׁעֲמֵם", russian: "скучный", category: "прилагательные" },
  { hebrew: "יָקָר", russian: "дорогой", category: "прилагательные" },
  { hebrew: "זוֹל", russian: "дешёвый", category: "прилагательные" },
  { hebrew: "עָשִׁיר", russian: "богатый", category: "прилагательные" },
  { hebrew: "עָנִי", russian: "бедный", category: "прилагательные" },
  { hebrew: "מָלֵא", russian: "полный", category: "прилагательные" },
  { hebrew: "רֵיק", russian: "пустой", category: "прилагательные" },
  { hebrew: "פָּתוּחַ", russian: "открытый", category: "прилагательные" },
  { hebrew: "סָגוּר", russian: "закрытый", category: "прилагательные" },
  { hebrew: "יָבֵשׁ", russian: "сухой", category: "прилагательные" },
  { hebrew: "רָטֹב", russian: "мокрый", category: "прилагательные" },
  { hebrew: "נָקִי", russian: "чистый", category: "прилагательные" },
  { hebrew: "מְלֻכְלָךְ", russian: "грязный", category: "прилагательные" },
  { hebrew: "שָׁקֵט", russian: "тихий", category: "прилагательные" },
  { hebrew: "רוֹעֵשׁ", russian: "шумный", category: "прилагательные" },
  { hebrew: "מָתוֹק", russian: "сладкий", category: "прилагательные" },
  { hebrew: "מָלוּחַ", russian: "солёный", category: "прилагательные" },
  { hebrew: "חָמוּץ", russian: "кислый", category: "прилагательные" },
  { hebrew: "חָרִיף", russian: "острый (вкус)", category: "прилагательные" },
  { hebrew: "מַר", russian: "горький", category: "прилагательные" },
  { hebrew: "בָּהִיר", russian: "светлый", category: "прилагательные" },
  { hebrew: "כָּהֶה", russian: "тёмный", category: "прилагательные" },

  // ===== Предлоги, союзы, наречия =====
  { hebrew: "שֶׁל", russian: "принадлежность (чей)", category: "служебные" },
  { hebrew: "עַל", russian: "на / о", category: "служебные" },
  { hebrew: "עִם", russian: "с (вместе)", category: "служебные" },
  { hebrew: "בְּלִי", russian: "без", category: "служебные" },
  { hebrew: "בֵּין", russian: "между", category: "служебные" },
  { hebrew: "לִפְנֵי", russian: "перед / до", category: "служебные" },
  { hebrew: "אַחֲרֵי", russian: "после", category: "служебные" },
  { hebrew: "מֵעַל", russian: "над", category: "служебные" },
  { hebrew: "מִתַּחַת", russian: "под", category: "служебные" },
  { hebrew: "לְיַד", russian: "рядом с", category: "служебные" },
  { hebrew: "מוּל", russian: "напротив", category: "служебные" },
  { hebrew: "בִּגְלַל", russian: "из-за", category: "служебные" },
  { hebrew: "בִּשְׁבִיל", russian: "для / ради", category: "служебные" },
  { hebrew: "כְּמוֹ", russian: "как / подобно", category: "служебные" },
  { hebrew: "גַּם", russian: "тоже / также", category: "служебные" },
  { hebrew: "אֲבָל", russian: "но", category: "служебные" },
  { hebrew: "אוֹ", russian: "или", category: "служебные" },
  { hebrew: "כִּי", russian: "потому что", category: "служебные" },
  { hebrew: "אִם", russian: "если", category: "служебные" },
  { hebrew: "רַק", russian: "только", category: "служебные" },
  { hebrew: "כָּל", russian: "весь / каждый", category: "служебные" },
  { hebrew: "הַרְבֵּה", russian: "много", category: "служебные" },
  { hebrew: "מְעַט", russian: "мало", category: "служебные" },
  { hebrew: "מְאוֹד", russian: "очень", category: "служебные" },
  { hebrew: "עוֹד", russian: "ещё", category: "служебные" },
  { hebrew: "כְּבָר", russian: "уже", category: "служебные" },
  { hebrew: "עֲדַיִן", russian: "ещё (пока)", category: "служебные" },
  { hebrew: "כָּאן", russian: "здесь", category: "служебные" },
  { hebrew: "שָׁם", russian: "там", category: "служебные" },
  { hebrew: "שׁוּב", russian: "снова", category: "служебные" },
  { hebrew: "בִּפְנִים", russian: "внутри", category: "служебные" },
  { hebrew: "בַּחוּץ", russian: "снаружи", category: "служебные" },
  { hebrew: "לְמַעְלָה", russian: "вверху / наверх", category: "служебные" },
  { hebrew: "לְמַטָּה", russian: "внизу / вниз", category: "служебные" },
  { hebrew: "יַחַד", russian: "вместе", category: "служебные" },
  { hebrew: "לְבַד", russian: "один / в одиночку", category: "служебные" },
  { hebrew: "בְּעֶרֶךְ", russian: "примерно / около", category: "служебные" },
  { hebrew: "מַמָּשׁ", russian: "действительно / реально", category: "служебные" },
  { hebrew: "כָּכָה", russian: "так / таким образом", category: "служебные" },
  { hebrew: "לְאַט", russian: "медленно", category: "служебные" },
  { hebrew: "מַהֵר", russian: "быстро", category: "служебные" },

  // ===== Образование =====
  { hebrew: "סֵפֶר", russian: "книга", category: "образование" },
  { hebrew: "מַחְבֶּרֶת", russian: "тетрадь", category: "образование" },
  { hebrew: "עֵט", russian: "ручка", category: "образование" },
  { hebrew: "עִפָּרוֹן", russian: "карандаш", category: "образование" },
  { hebrew: "מַחַק", russian: "ластик", category: "образование" },
  { hebrew: "סַרְגֵּל", russian: "линейка", category: "образование" },
  { hebrew: "לוּחַ", russian: "доска", category: "образование" },
  { hebrew: "כִּתָּה", russian: "класс", category: "образование" },
  { hebrew: "שִׁעוּר", russian: "урок", category: "образование" },
  { hebrew: "בְּחִינָה", russian: "экзамен", category: "образование" },
  { hebrew: "צִיּוּן", russian: "оценка", category: "образование" },
  { hebrew: "שְׁאֵלָה", russian: "вопрос", category: "образование" },
  { hebrew: "תְּשׁוּבָה", russian: "ответ", category: "образование" },
  { hebrew: "שָׂפָה", russian: "язык (речь)", category: "образование" },
  { hebrew: "מִלָּה", russian: "слово", category: "образование" },
  { hebrew: "מִשְׁפָּט", russian: "предложение", category: "образование" },
  { hebrew: "סִפּוּר", russian: "рассказ / история", category: "образование" },
  { hebrew: "הִיסְטוֹרְיָה", russian: "история (наука)", category: "образование" },
  { hebrew: "מָתֵמָטִיקָה", russian: "математика", category: "образование" },
  { hebrew: "מַדָּע", russian: "наука", category: "образование" },
  { hebrew: "אָמָּנוּת", russian: "искусство", category: "образование" },
  { hebrew: "מוּסִיקָה", russian: "музыка", category: "образование" },
  { hebrew: "סְפוֹרְט", russian: "спорт", category: "образование" },
  { hebrew: "גֵּיאוֹגְרָפְיָה", russian: "география", category: "образование" },
  { hebrew: "אוֹת", russian: "буква", category: "образование" },

  // ===== Здоровье =====
  { hebrew: "בְּרִיאוּת", russian: "здоровье", category: "здоровье" },
  { hebrew: "מַחֲלָה", russian: "болезнь", category: "здоровье" },
  { hebrew: "כְּאֵב", russian: "боль", category: "здоровье" },
  { hebrew: "רוֹפֵא שִׁנַּיִם", russian: "стоматолог", category: "здоровье" },
  { hebrew: "תְּרוּפָה", russian: "лекарство", category: "здоровье" },
  { hebrew: "בֵּית מִרְקַחַת", russian: "аптека", category: "здоровье" },
  { hebrew: "חֹם", russian: "температура / жар", category: "здоровье" },
  { hebrew: "שִׁעוּל", russian: "кашель", category: "здоровье" },
  { hebrew: "הַצְטַנְּנוּת", russian: "простуда", category: "здоровье" },
  { hebrew: "כְּאֵב רֹאשׁ", russian: "головная боль", category: "здоровье" },
  { hebrew: "כְּאֵב בֶּטֶן", russian: "боль в животе", category: "здоровье" },
  { hebrew: "נִיתּוּחַ", russian: "операция", category: "здоровье" },
  { hebrew: "תַּחְבֹּשֶׁת", russian: "повязка / бинт", category: "здоровье" },
  { hebrew: "זְרִיקָה", russian: "укол", category: "здоровье" },
  { hebrew: "אַלֶּרְגְּיָה", russian: "аллергия", category: "здоровье" },
  { hebrew: "כַּדּוּר", russian: "таблетка / мяч", category: "здоровье" },
  { hebrew: "מִשְׁקָל", russian: "вес", category: "здоровье" },

  // ===== Покупки и деньги =====
  { hebrew: "כֶּסֶף", russian: "деньги / серебро", category: "покупки" },
  { hebrew: "מַטְבֵּעַ", russian: "монета", category: "покупки" },
  { hebrew: "שְׁטָר", russian: "купюра / банкнота", category: "покупки" },
  { hebrew: "מְחִיר", russian: "цена", category: "покупки" },
  { hebrew: "הֲנָחָה", russian: "скидка", category: "покупки" },
  { hebrew: "חֶשְׁבּוֹן", russian: "счёт", category: "покупки" },
  { hebrew: "כַּרְטִיס אַשְׁרַאי", russian: "кредитная карта", category: "покупки" },
  { hebrew: "קַבָּלָה", russian: "чек / квитанция", category: "покупки" },
  { hebrew: "קַנְיוֹן", russian: "торговый центр", category: "покупки" },
  { hebrew: "מוֹכֵר", russian: "продавец", category: "покупки" },
  { hebrew: "קוֹנֶה", russian: "покупатель", category: "покупки" },
  { hebrew: "מַתָּנָה", russian: "подарок", category: "покупки" },

  // ===== Спорт и хобби =====
  { hebrew: "כַּדּוּרֶגֶל", russian: "футбол", category: "спорт" },
  { hebrew: "כַּדּוּרְסַל", russian: "баскетбол", category: "спорт" },
  { hebrew: "שְׂחִיָּה", russian: "плавание", category: "спорт" },
  { hebrew: "רִיצָה", russian: "бег", category: "спорт" },
  { hebrew: "הֲלִיכָה", russian: "ходьба", category: "спорт" },
  { hebrew: "טִיּוּל", russian: "поход / прогулка", category: "спорт" },
  { hebrew: "מִשְׂחָק", russian: "игра", category: "спорт" },
  { hebrew: "קְבוּצָה", russian: "команда", category: "спорт" },
  { hebrew: "מְנַצֵּחַ", russian: "победитель", category: "спорт" },
  { hebrew: "אַלּוּף", russian: "чемпион", category: "спорт" },
  { hebrew: "תַּחֲרוּת", russian: "соревнование", category: "спорт" },

  // ===== Технологии =====
  { hebrew: "מַחְשֵׁב", russian: "компьютер", category: "технологии" },
  { hebrew: "טֶלֶפוֹן", russian: "телефон", category: "технологии" },
  { hebrew: "אִינְטֶרְנֶט", russian: "интернет", category: "технологии" },
  { hebrew: "דֹּאַר אֶלֶקְטְרוֹנִי", russian: "электронная почта", category: "технологии" },
  { hebrew: "הוֹדָעָה", russian: "сообщение", category: "технологии" },
  { hebrew: "אַפְּלִיקַצְיָה", russian: "приложение", category: "технологии" },
  { hebrew: "מָסָךְ", russian: "экран", category: "технологии" },
  { hebrew: "מַקְלֶדֶת", russian: "клавиатура", category: "технологии" },
  { hebrew: "עַכְבָּר", russian: "мышка (компьютерная)", category: "технологии" },
  { hebrew: "מַדְפֶּסֶת", russian: "принтер", category: "технологии" },
  { hebrew: "תָּכְנָה", russian: "программа", category: "технологии" },
  { hebrew: "סִיסְמָה", russian: "пароль", category: "технологии" },
  { hebrew: "רֶשֶׁת", russian: "сеть", category: "технологии" },
  { hebrew: "תְּמוּנָה", russian: "фотография / картинка", category: "технологии" },
  { hebrew: "מִכְתָּב", russian: "письмо", category: "технологии" },

  // ===== Работа =====
  { hebrew: "עֲבוֹדָה", russian: "работа", category: "работа" },
  { hebrew: "פְּגִישָׁה", russian: "встреча", category: "работа" },
  { hebrew: "פְּרוֹיֶקְט", russian: "проект", category: "работа" },
  { hebrew: "מַשְׂכֹּרֶת", russian: "зарплата", category: "работа" },
  { hebrew: "בּוֹס", russian: "начальник", category: "работа" },
  { hebrew: "עוֹבֵד", russian: "работник", category: "работа" },
  { hebrew: "צָוֶות", russian: "команда (рабочая)", category: "работа" },
  { hebrew: "חֻפְשָׁה", russian: "отпуск", category: "работа" },
  { hebrew: "רֵאָיוֹן", russian: "собеседование", category: "работа" },
  { hebrew: "חוֹזֶה", russian: "договор / контракт", category: "работа" },
  { hebrew: "מְשִׁימָה", russian: "задача", category: "работа" },
  { hebrew: "יְשִׁיבָה", russian: "заседание / совещание", category: "работа" },

  // ===== Разное =====
  { hebrew: "דָּבָר", russian: "вещь", category: "разное" },
  { hebrew: "מָקוֹם", russian: "место", category: "разное" },
  { hebrew: "צַד", russian: "сторона", category: "разное" },
  { hebrew: "סוֹף", russian: "конец", category: "разное" },
  { hebrew: "הַתְחָלָה", russian: "начало", category: "разное" },
  { hebrew: "חֵלֶק", russian: "часть", category: "разное" },
  { hebrew: "סוּג", russian: "вид / тип", category: "разное" },
  { hebrew: "צוּרָה", russian: "форма", category: "разное" },
  { hebrew: "גֹּדֶל", russian: "размер", category: "разное" },
  { hebrew: "קוֹל", russian: "голос / звук", category: "разное" },
  { hebrew: "רֵיחַ", russian: "запах", category: "разное" },
  { hebrew: "טַעַם", russian: "вкус", category: "разное" },
  { hebrew: "שֵׁם", russian: "имя", category: "разное" },
  { hebrew: "גִּיל", russian: "возраст", category: "разное" },
  { hebrew: "מִסְפָּר", russian: "число / номер", category: "разное" },
  { hebrew: "עַמּוּד", russian: "страница / столб", category: "разное" },
  { hebrew: "בְּעָיָה", russian: "проблема", category: "разное" },
  { hebrew: "פִּתָרוֹן", russian: "решение", category: "разное" },
  { hebrew: "רַעְיוֹן", russian: "идея", category: "разное" },
  { hebrew: "חֲלוֹם", russian: "мечта / сон", category: "разное" },
  { hebrew: "חַיִּים", russian: "жизнь", category: "разное" },
  { hebrew: "מָוֶת", russian: "смерть", category: "разное" },
  { hebrew: "חֹפֶשׁ", russian: "свобода", category: "разное" },
  { hebrew: "מִלְחָמָה", russian: "война", category: "разное" },
  { hebrew: "שָׁלוֹם", russian: "мир (отсутствие войны)", category: "разное" },
  { hebrew: "חוֹק", russian: "закон", category: "разное" },
  { hebrew: "זְכוּת", russian: "право / привилегия", category: "разное" },
  { hebrew: "אֱמֶת", russian: "правда", category: "разное" },
  { hebrew: "שֶׁקֶר", russian: "ложь", category: "разное" },
  { hebrew: "סוֹד", russian: "секрет / тайна", category: "разное" },
  { hebrew: "כֹּחַ", russian: "сила", category: "разное" },
  { hebrew: "חָכְמָה", russian: "мудрость", category: "разное" },
  { hebrew: "דַּעַת", russian: "мнение / знание", category: "разное" },
  { hebrew: "תַּרְבּוּת", russian: "культура", category: "разное" },
  { hebrew: "דָּת", russian: "религия", category: "разное" },
  { hebrew: "אֱלֹהִים", russian: "Бог", category: "разное" },
  { hebrew: "עוֹלָם", russian: "мир / вселенная", category: "разное" },
  { hebrew: "טֶבַע", russian: "природа", category: "разное" },
  { hebrew: "חֶבְרָה", russian: "общество / компания", category: "разное" },
  { hebrew: "מֶמְשָׁלָה", russian: "правительство", category: "разное" },
  { hebrew: "חֲדָשׁוֹת", russian: "новости", category: "разное" },
  { hebrew: "עִתּוֹן", russian: "газета", category: "разное" },
  { hebrew: "סֶרֶט", russian: "фильм", category: "разное" },
  { hebrew: "שִׁיר", russian: "песня / стихотворение", category: "разное" },
  { hebrew: "צִיּוּר", russian: "рисунок", category: "разное" },
  { hebrew: "מִפָּה", russian: "карта (географ.)", category: "разное" },
  { hebrew: "דֶּגֶל", russian: "флаг", category: "разное" },
  { hebrew: "מִלּוֹן", russian: "словарь", category: "разное" },
  { hebrew: "יוֹם הֻלֶּדֶת", russian: "день рождения", category: "разное" },
  { hebrew: "חֲתוּנָה", russian: "свадьба", category: "разное" },
  { hebrew: "חָג", russian: "праздник", category: "разное" },

  // ===== Дополнительные глаголы =====
  { hebrew: "לָגֶשֶׁת", russian: "подходить", category: "глаголы" },
  { hebrew: "לְהִתְקַדֵּם", russian: "продвигаться", category: "глаголы" },
  { hebrew: "לְהַצְלִיחַ", russian: "преуспевать / удаваться", category: "глаголы" },
  { hebrew: "לְהִכָּשֵׁל", russian: "терпеть неудачу", category: "глаголы" },
  { hebrew: "לְהַשְׁפִּיעַ", russian: "влиять", category: "глаголы" },
  { hebrew: "לִסְבֹּל", russian: "страдать / терпеть", category: "глаголы" },
  { hebrew: "לְהַנּוֹת", russian: "наслаждаться", category: "глаголы" },
  { hebrew: "לְהַכִּיר", russian: "знакомиться / узнавать", category: "глаголы" },
  { hebrew: "לְהַסְכִּים", russian: "соглашаться", category: "глаголы" },
  { hebrew: "לְסָרֵב", russian: "отказывать(ся)", category: "глаголы" },
  { hebrew: "לְהַבְטִיחַ", russian: "обещать", category: "глаголы" },
  { hebrew: "לְאַיֵּם", russian: "угрожать", category: "глаголы" },
  { hebrew: "לִכְעוֹס", russian: "злиться", category: "глаголы" },
  { hebrew: "לְהִתְנַצֵּל", russian: "извиняться", category: "глаголы" },
  { hebrew: "לְהוֹדוֹת", russian: "благодарить", category: "глаголы" },
  { hebrew: "לְהַזְהִיר", russian: "предупреждать", category: "глаголы" },
  { hebrew: "לְהַצִּיל", russian: "спасать", category: "глаголы" },
  { hebrew: "לְאַבֵּד", russian: "терять", category: "глаголы" },
  { hebrew: "לְהַחְזִיר", russian: "возвращать (что-то)", category: "глаголы" },
  { hebrew: "לְהַלְווֹת", russian: "одалживать", category: "глаголы" },
  { hebrew: "לִשְׁלוֹט", russian: "контролировать / править", category: "глаголы" },
  { hebrew: "לְהוֹבִיל", russian: "вести / руководить", category: "глаголы" },
  { hebrew: "לְהִצְטָרֵף", russian: "присоединяться", category: "глаголы" },
  { hebrew: "לִפְחוֹד", russian: "бояться", category: "глаголы" },
  { hebrew: "לְהִתְאַמֵּן", russian: "тренироваться", category: "глаголы" },
  { hebrew: "לִשְׁקוֹל", russian: "взвешивать", category: "глаголы" },
  { hebrew: "לָמוֹד", russian: "измерять", category: "глаголы" },
  { hebrew: "לְהַכִּין", russian: "готовить / подготавливать", category: "глаголы" },
  { hebrew: "לְסַדֵּר", russian: "упорядочивать / убирать", category: "глаголы" },
  { hebrew: "לְעַצֵּב", russian: "дизайнить / формировать", category: "глаголы" },
  { hebrew: "לְהַרְוִיחַ", russian: "зарабатывать / выигрывать", category: "глаголы" },
  { hebrew: "לְהוֹצִיא", russian: "тратить / вынимать", category: "глаголы" },
  { hebrew: "לְהַכְנִיס", russian: "вводить / вносить", category: "глаголы" },
  { hebrew: "לַעֲלוֹת", russian: "подниматься / стоить", category: "глаголы" },
  { hebrew: "לָרֶדֶת", russian: "спускаться", category: "глаголы" },
  { hebrew: "לִנְפֹּל", russian: "падать", category: "глаголы" },
  { hebrew: "לִקְפֹּץ", russian: "прыгать", category: "глаголы" },
  { hebrew: "לִשְׂחוֹת", russian: "плавать", category: "глаголы" },
  { hebrew: "לַחְתֹּם", russian: "подписывать", category: "глаголы" },
  { hebrew: "לְהַדְפִּיס", russian: "печатать", category: "глаголы" },
  { hebrew: "לְצַלֵּם", russian: "фотографировать", category: "глаголы" },
  { hebrew: "לִשְׁלוֹחַ", russian: "посылать", category: "глаголы" },
  { hebrew: "לְהִתְקַשֵּׁר", russian: "звонить / связываться", category: "глаголы" },
  { hebrew: "לְהִזָּהֵר", russian: "остерегаться", category: "глаголы" },
  { hebrew: "לִנְעוֹל", russian: "запирать", category: "глаголы" },

  // ===== Кухня и посуда =====
  { hebrew: "צַלַּחַת", russian: "тарелка", category: "кухня" },
  { hebrew: "כּוֹס", russian: "стакан", category: "кухня" },
  { hebrew: "סְפָל", russian: "кружка / чашка", category: "кухня" },
  { hebrew: "מַזְלֵג", russian: "вилка", category: "кухня" },
  { hebrew: "סַכִּין", russian: "нож", category: "кухня" },
  { hebrew: "כַּף", russian: "ложка", category: "кухня" },
  { hebrew: "סִיר", russian: "кастрюля", category: "кухня" },
  { hebrew: "מַחֲבַת", russian: "сковорода", category: "кухня" },
  { hebrew: "קוּמְקוּם", russian: "чайник", category: "кухня" },
  { hebrew: "קְעָרָה", russian: "миска", category: "кухня" },
  { hebrew: "מַפִּית", russian: "салфетка", category: "кухня" },
  { hebrew: "מַפָּה", russian: "скатерть", category: "кухня" },
  { hebrew: "בַּקְבּוּק", russian: "бутылка", category: "кухня" },
  { hebrew: "פּוֹתְחָן", russian: "открывалка", category: "кухня" },
  { hebrew: "מִקְרוֹגַּל", russian: "микроволновка", category: "кухня" },

  // ===== Материалы =====
  { hebrew: "עֵץ", russian: "древесина / дерево", category: "материалы" },
  { hebrew: "בַּרְזֶל", russian: "железо", category: "материалы" },
  { hebrew: "זְכוּכִית", russian: "стекло", category: "материалы" },
  { hebrew: "נְיָר", russian: "бумага", category: "материалы" },
  { hebrew: "בַּד", russian: "ткань", category: "материалы" },
  { hebrew: "פְּלָסְטִיק", russian: "пластик", category: "материалы" },
  { hebrew: "גוּמִי", russian: "резина", category: "материалы" },
  { hebrew: "חֶרֶס", russian: "глина / керамика", category: "материалы" },
  { hebrew: "עוֹר", russian: "кожа (материал)", category: "материалы" },
  { hebrew: "צֶמֶר", russian: "шерсть", category: "материалы" },
  { hebrew: "כֹּתֶן", russian: "хлопок", category: "материалы" },
  { hebrew: "מֶשִׁי", russian: "шёлк", category: "материалы" },
  { hebrew: "בֶּטוֹן", russian: "бетон", category: "материалы" },
  { hebrew: "נְחוֹשֶׁת", russian: "медь", category: "материалы" },

  // ===== Формы и направления =====
  { hebrew: "עִיגּוּל", russian: "круг", category: "формы" },
  { hebrew: "רִיבּוּעַ", russian: "квадрат", category: "формы" },
  { hebrew: "מְשֻׁלָּשׁ", russian: "треугольник", category: "формы" },
  { hebrew: "קַו", russian: "линия", category: "формы" },
  { hebrew: "נְקֻדָּה", russian: "точка", category: "формы" },
  { hebrew: "פִּנָּה", russian: "угол", category: "формы" },
  { hebrew: "צָפוֹן", russian: "север", category: "формы" },
  { hebrew: "דָּרוֹם", russian: "юг", category: "формы" },
  { hebrew: "מִזְרָח", russian: "восток", category: "формы" },
  { hebrew: "מַעֲרָב", russian: "запад", category: "формы" },
  { hebrew: "יָמִין", russian: "право", category: "формы" },
  { hebrew: "שְׂמֹאל", russian: "лево", category: "формы" },
  { hebrew: "יָשָׁר", russian: "прямо", category: "формы" },

  // ===== Месяцы =====
  { hebrew: "יָנוּאָר", russian: "январь", category: "месяцы" },
  { hebrew: "פֶבְּרוּאָר", russian: "февраль", category: "месяцы" },
  { hebrew: "מֶרְץ", russian: "март", category: "месяцы" },
  { hebrew: "אַפְּרִיל", russian: "апрель", category: "месяцы" },
  { hebrew: "מַאי", russian: "май", category: "месяцы" },
  { hebrew: "יוּנִי", russian: "июнь", category: "месяцы" },
  { hebrew: "יוּלִי", russian: "июль", category: "месяцы" },
  { hebrew: "אוֹגוּסְט", russian: "август", category: "месяцы" },
  { hebrew: "סֶפְּטֶמְבֶּר", russian: "сентябрь", category: "месяцы" },
  { hebrew: "אוֹקְטוֹבֶּר", russian: "октябрь", category: "месяцы" },
  { hebrew: "נוֹבֶמְבֶּר", russian: "ноябрь", category: "месяцы" },
  { hebrew: "דֶּצֶמְבֶּר", russian: "декабрь", category: "месяцы" },

  // ===== Музыкальные инструменты =====
  { hebrew: "פְּסַנְתֵּר", russian: "пианино", category: "музыка" },
  { hebrew: "גִּיטָרָה", russian: "гитара", category: "музыка" },
  { hebrew: "כִּנּוֹר", russian: "скрипка", category: "музыка" },
  { hebrew: "חֲלִיל", russian: "флейта", category: "музыка" },
  { hebrew: "תֹּף", russian: "барабан", category: "музыка" },
  { hebrew: "חֲצוֹצְרָה", russian: "труба", category: "музыка" },

  // ===== Дополнительные прилагательные =====
  { hebrew: "נוֹרָא", russian: "ужасный / очень", category: "прилагательные" },
  { hebrew: "נִפְלָא", russian: "чудесный", category: "прилагательные" },
  { hebrew: "נֶהְדָּר", russian: "великолепный", category: "прилагательные" },
  { hebrew: "מְצוּיָן", russian: "отличный", category: "прилагательные" },
  { hebrew: "מוּזָר", russian: "странный", category: "прилагательные" },
  { hebrew: "רְגִיל", russian: "обычный / привычный", category: "прилагательные" },
  { hebrew: "מְסֻכָּן", russian: "опасный", category: "прилагательные" },
  { hebrew: "בָּטוּחַ", russian: "безопасный / уверенный", category: "прилагательные" },
  { hebrew: "חָפְשִׁי", russian: "свободный", category: "прилагательные" },
  { hebrew: "עָסוּק", russian: "занятой", category: "прилагательные" },
  { hebrew: "פָּנוּי", russian: "свободный / незанятый", category: "прилагательные" },
  { hebrew: "מוּכָן", russian: "готовый", category: "прилагательные" },
  { hebrew: "אָסוּר", russian: "запрещённый", category: "прилагательные" },
  { hebrew: "מֻתָּר", russian: "разрешённый", category: "прилагательные" },
  { hebrew: "חָדָשׁ", russian: "острый (лезвие)", category: "прилагательные" },
  { hebrew: "עָגֹל", russian: "круглый", category: "прилагательные" },
  { hebrew: "שָׁטוּחַ", russian: "плоский", category: "прилагательные" },
  { hebrew: "עָמֹק", russian: "глубокий", category: "прилагательные" },
  { hebrew: "רָדוּד", russian: "мелкий (неглубокий)", category: "прилагательные" },
  { hebrew: "עָבֶה", russian: "толстый", category: "прилагательные" },
  { hebrew: "דַּק", russian: "тонкий", category: "прилагательные" },
  { hebrew: "חַד", russian: "острый (предмет)", category: "прилагательные" },
  { hebrew: "קֵהֶה", russian: "тупой (предмет)", category: "прилагательные" },
  { hebrew: "אָמִיתִי", russian: "настоящий", category: "прилагательные" },
  { hebrew: "מְזֻיָּף", russian: "поддельный", category: "прилагательные" },

  // ===== Дополнительная еда =====
  { hebrew: "קְרֶם", russian: "крем / сливки", category: "еда" },
  { hebrew: "שְׁמֶנֶת", russian: "сметана", category: "еда" },
  { hebrew: "יוֹגוּרְט", russian: "йогурт", category: "еда" },
  { hebrew: "קֶטְשָׁפּ", russian: "кетчуп", category: "еда" },
  { hebrew: "חַרְדָּל", russian: "горчица", category: "еда" },
  { hebrew: "אָטְרִיוֹת", russian: "лапша / макароны", category: "еда" },
  { hebrew: "קֻסְקוּס", russian: "кускус", category: "еда" },
  { hebrew: "תִּירָס", russian: "кукуруза", category: "еда" },
  { hebrew: "זַיִת", russian: "маслина / олива", category: "еда" },
  { hebrew: "חוּמוּס (קִטְנִיָּה)", russian: "нут", category: "еда" },
  { hebrew: "עֲדָשִׁים", russian: "чечевица", category: "еда" },
  { hebrew: "שְׁקֵדִים", russian: "миндаль", category: "еда" },
  { hebrew: "בּוֹטְנִים", russian: "арахис", category: "еда" },
  { hebrew: "צִימוּקִים", russian: "изюм", category: "еда" },
  { hebrew: "תְּמָרִים", russian: "финики", category: "еда" },
  { hebrew: "תְּאֵנָה", russian: "инжир", category: "еда" },
  { hebrew: "רִמּוֹן", russian: "гранат", category: "еда" },
  { hebrew: "דֻּבְדְּבָן", russian: "вишня", category: "еда" },
  { hebrew: "שְׁזִיף", russian: "слива", category: "еда" },
  { hebrew: "חֲצִיל", russian: "баклажан", category: "еда" },
  { hebrew: "כְּרוּב", russian: "капуста", category: "еда" },
  { hebrew: "בְּרוֹקוֹלִי", russian: "брокколи", category: "еда" },
  { hebrew: "תֶּרֶד", russian: "шпинат", category: "еда" },
  { hebrew: "כּוּסְבָּרָה", russian: "кориандр / кинза", category: "еда" },
  { hebrew: "נַעֲנָע", russian: "мята", category: "еда" },

  // ===== Дополнительные животные и насекомые =====
  { hebrew: "חֲמוֹר", russian: "осёл", category: "животные" },
  { hebrew: "צְבִי", russian: "олень", category: "животные" },
  { hebrew: "קִיפּוֹד", russian: "ёж", category: "животные" },
  { hebrew: "עֲטַלֵּף", russian: "летучая мышь", category: "животные" },
  { hebrew: "לִוְיָתָן", russian: "кит", category: "животные" },
  { hebrew: "דּוֹלְפִין", russian: "дельфин", category: "животные" },
  { hebrew: "כְּרִישׁ", russian: "акула", category: "животные" },
  { hebrew: "תַּנִּין", russian: "крокодил", category: "животные" },
  { hebrew: "צְפַרְדֵּעַ", russian: "лягушка", category: "животные" },
  { hebrew: "תּוּכִּי", russian: "попугай", category: "животные" },
  { hebrew: "עוֹרֵב", russian: "ворон", category: "животные" },
  { hebrew: "חֲסִידָה", russian: "аист", category: "животные" },
  { hebrew: "יַתּוּשׁ", russian: "комар", category: "животные" },
  { hebrew: "זְבוּב", russian: "муха", category: "животные" },
  { hebrew: "חִפּוּשִׁית", russian: "жук", category: "животные" },
  { hebrew: "שִׁפְשֵׁף", russian: "ящерица", category: "животные" },
  { hebrew: "נָמֵר", russian: "тигр / леопард", category: "животные" },
  { hebrew: "קַנְגּוּרוּ", russian: "кенгуру", category: "животные" },
  { hebrew: "פִּינְגְּוִין", russian: "пингвин", category: "животные" },

  // ===== Дополнительные места и география =====
  { hebrew: "יַבֶּשֶׁת", russian: "континент / суша", category: "география" },
  { hebrew: "חֶצִי אִי", russian: "полуостров", category: "география" },
  { hebrew: "מַעְיָן", russian: "родник / источник", category: "география" },
  { hebrew: "מַפָּל", russian: "водопад", category: "география" },
  { hebrew: "עֵמֶק", russian: "долина", category: "география" },
  { hebrew: "מְעָרָה", russian: "пещера", category: "география" },
  { hebrew: "חוֹף יָם", russian: "морской берег", category: "география" },
  { hebrew: "שָׂדֶה", russian: "поле", category: "география" },
  { hebrew: "נָאזִיס", russian: "оазис", category: "география" },
  { hebrew: "צוּק", russian: "утёс / обрыв", category: "география" },

  // ===== Дополнительные абстрактные понятия =====
  { hebrew: "הַצְלָחָה", russian: "успех", category: "разное" },
  { hebrew: "כִּשָׁלוֹן", russian: "неудача / провал", category: "разное" },
  { hebrew: "נִסָּיוֹן", russian: "опыт / попытка", category: "разное" },
  { hebrew: "הִזְדַּמְנוּת", russian: "возможность / шанс", category: "разное" },
  { hebrew: "סִיכּוּן", russian: "риск", category: "разное" },
  { hebrew: "סַכָּנָה", russian: "опасность", category: "разное" },
  { hebrew: "בְּטִיחוּת", russian: "безопасность", category: "разное" },
  { hebrew: "אַחְרָיוּת", russian: "ответственность", category: "разное" },
  { hebrew: "חוֹבָה", russian: "обязанность / долг", category: "разное" },
  { hebrew: "סַבְלָנוּת", russian: "терпение", category: "разное" },
  { hebrew: "כָּבוֹד", russian: "уважение / честь", category: "разное" },
  { hebrew: "אֵמוּן", russian: "доверие", category: "разное" },
  { hebrew: "יַחַס", russian: "отношение", category: "разное" },
  { hebrew: "קֶשֶׁר", russian: "связь", category: "разное" },
  { hebrew: "הֶבְדֵּל", russian: "различие", category: "разное" },
  { hebrew: "דִּמְיוֹן", russian: "сходство / воображение", category: "разное" },
  { hebrew: "מַטָּרָה", russian: "цель", category: "разное" },
  { hebrew: "תָּכְנִית", russian: "план / программа", category: "разное" },
  { hebrew: "שִׁנּוּי", russian: "изменение", category: "разное" },
  { hebrew: "הַחְלָטָה", russian: "решение (принятое)", category: "разное" },
  { hebrew: "בְּחִירָה", russian: "выбор", category: "разное" },
  { hebrew: "תְּנוּעָה", russian: "движение", category: "разное" },
  { hebrew: "מַהִירוּת", russian: "скорость", category: "разное" },
  { hebrew: "מֶרְחָק", russian: "расстояние", category: "разное" },
  { hebrew: "גֹּבַהּ", russian: "высота", category: "разное" },
  { hebrew: "עֹמֶק", russian: "глубина", category: "разное" },
  { hebrew: "רֹחַב", russian: "ширина", category: "разное" },
  { hebrew: "אֹרֶךְ", russian: "длина", category: "разное" },
  { hebrew: "שֶׁטַח", russian: "площадь / территория", category: "разное" },
  { hebrew: "גְּבוּל", russian: "граница", category: "разное" },
  { hebrew: "מֶרְכָּז", russian: "центр", category: "разное" },
  { hebrew: "קָצֶה", russian: "край / конец", category: "разное" },

  // ===== Дополнительные фразы и выражения =====
  { hebrew: "מָה נִשְׁמָע", russian: "как дела? (разг.)", category: "фразы" },
  { hebrew: "אֵין בְּעָיָה", russian: "нет проблем", category: "фразы" },
  { hebrew: "לֹא נוֹרָא", russian: "ничего страшного", category: "фразы" },
  { hebrew: "בְּבַקָּשָׁה, דַּבֵּר לְאַט", russian: "пожалуйста, говори медленно", category: "фразы" },
  { hebrew: "אֲנִי לֹא מֵבִין", russian: "я не понимаю (м.)", category: "фразы" },
  { hebrew: "אֲנִי לֹא מְבִינָה", russian: "я не понимаю (ж.)", category: "фразы" },
  { hebrew: "כַּמָּה זֶה עוֹלֶה", russian: "сколько это стоит?", category: "фразы" },
  { hebrew: "אֵיפֹה הַשֵּׁירוּתִים", russian: "где туалет?", category: "фразы" },
  { hebrew: "עֶזְרָה", russian: "помощь!", category: "фразы" },
  { hebrew: "בְּהַצְלָחָה רַבָּה", russian: "большой удачи", category: "фразы" },
  { hebrew: "אֵין מַה לַעֲשׂוֹת", russian: "ничего не поделаешь", category: "фразы" },
  { hebrew: "כָּל הַכָּבוֹד", russian: "молодец / браво", category: "фразы" },

  // ===== Дополнительное здоровье =====
  { hebrew: "דִּיאֵטָה", russian: "диета", category: "здоровье" },
  { hebrew: "חִסּוּן", russian: "прививка / вакцинация", category: "здоровье" },
  { hebrew: "דֹּפֶק", russian: "пульс", category: "здоровье" },
  { hebrew: "לַחַץ דָּם", russian: "давление крови", category: "здоровье" },
  { hebrew: "שִׁבָּר", russian: "перелом", category: "здоровье" },
  { hebrew: "צַלֶּקֶת", russian: "шрам", category: "здоровье" },
  { hebrew: "וִירוּס", russian: "вирус", category: "здоровье" },
  { hebrew: "חִידָּקִים", russian: "бактерии / микробы", category: "здоровье" },
  { hebrew: "אַנְטִיבְּיוֹטִיקָה", russian: "антибиотик", category: "здоровье" },

  // ===== Дополнительные технологии =====
  { hebrew: "מָחְשֵׁב נַיָּד", russian: "ноутбук", category: "технологии" },
  { hebrew: "טָאבְּלֶט", russian: "планшет", category: "технологии" },
  { hebrew: "אוֹזְנִיּוֹת", russian: "наушники", category: "технологии" },
  { hebrew: "רַמְקוֹל", russian: "колонка / динамик", category: "технологии" },
  { hebrew: "מַצְלֵמָה", russian: "камера", category: "технологии" },
  { hebrew: "סוֹלְלָה", russian: "батарейка / аккумулятор", category: "технологии" },
  { hebrew: "מַטְעֵן", russian: "зарядка / зарядное", category: "технологии" },
  { hebrew: "וִידֵאוֹ", russian: "видео", category: "технологии" },
  { hebrew: "אֲתַר אִינְטֶרְנֶט", russian: "веб-сайт", category: "технологии" },
  { hebrew: "קוֹבֶץ", russian: "файл", category: "технологии" },
  { hebrew: "תִּיקִיָּה", russian: "папка (компьютер)", category: "технологии" },
  { hebrew: "גִּיבּוּי", russian: "резервная копия", category: "технологии" },
  { hebrew: "עִדְכּוּן", russian: "обновление", category: "технологии" },
  { hebrew: "חִיפּוּשׂ", russian: "поиск", category: "технологии" },
  { hebrew: "הוֹרָדָה", russian: "скачивание", category: "технологии" },

  // ===== Дополнительные работа и экономика =====
  { hebrew: "תַּעֲשִׂיָּה", russian: "промышленность", category: "работа" },
  { hebrew: "מִסְחָר", russian: "торговля", category: "работа" },
  { hebrew: "יְצוּא", russian: "экспорт", category: "работа" },
  { hebrew: "יְבוּא", russian: "импорт", category: "работа" },
  { hebrew: "מַס", russian: "налог", category: "работа" },
  { hebrew: "הַלְוָאָה", russian: "ссуда / кредит", category: "работа" },
  { hebrew: "רֶוַח", russian: "прибыль", category: "работа" },
  { hebrew: "הֶפְסֵד", russian: "убыток", category: "работа" },
  { hebrew: "תַּקְצִיב", russian: "бюджет", category: "работа" },
  { hebrew: "הַשְׁקָעָה", russian: "инвестиция", category: "работа" },
  { hebrew: "פִּרְסוֹם", russian: "реклама", category: "работа" },
  { hebrew: "לָקוֹחַ", russian: "клиент", category: "работа" },
  { hebrew: "סְפָּק", russian: "поставщик", category: "работа" },

  // ===== Дополнительный спорт =====
  { hebrew: "כַּדּוּרְעַף", russian: "волейбол", category: "спорт" },
  { hebrew: "טֶנִיס", russian: "теннис", category: "спорт" },
  { hebrew: "הִתְעַמְּלוּת", russian: "гимнастика", category: "спорт" },
  { hebrew: "אִיגְרוּף", russian: "бокс", category: "спорт" },
  { hebrew: "יוֹגָה", russian: "йога", category: "спорт" },
  { hebrew: "גְּלִישָׁה", russian: "сёрфинг", category: "спорт" },
  { hebrew: "אַתְלֵטִיקָה", russian: "лёгкая атлетика", category: "спорт" },
  { hebrew: "גוֹל", russian: "гол", category: "спорт" },
  { hebrew: "שַׁעַר", russian: "ворота", category: "спорт" },
  { hebrew: "אַצְטַדְיוֹן", russian: "стадион", category: "спорт" },
];
